export const FETCH_ALL_CATEGORIES = "FETCH_ALL_CATEGORIES";
export const SET_SELECTED_CATEGORY = "FETCH_SELECTED_CATEGORY";

export const FETCH_PRODUCTS_BY_CATEGORY = "FETCH_ALL_PRODUCTS";
export const FETCH_PRODUCT_BY_ID = "FETCH_PRODUCT_BY_ID";

export const GET_ALL_CURRENCIES = "GET_SELECTED_CURRENCIES";
export const SET_SELECTED_CURRENCY = "SET_SELECTED_CURRENCY";

export const ADD_PRODUCT_TO_CART = "ADD_PRODUCT_TO_CART";
export const REMOVE_PRODUCT_FROM_CART = "REMOVE_PRODUCT_FROM_CART";
